
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pacientes;
import model.ListaPacientes;

public class TelaInicio extends javax.swing.JFrame {

    private final String[] tableColumns = {"Paciente", "Telefone", "CPF", "Data", "Já é Paciente?", "Consulta Realizada?"};
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);

    private List<Pacientes> pacientesLista = ListaPacientes.Listar();

    public TelaInicio() {
        initComponents();
    }
    
    private void finalizarConsulta(int posPaciente){
        if(posPaciente >= 0){
            DetalhesConsulta detalhes = new DetalhesConsulta();
            detalhes.mostraTela(this, posPaciente);
        }
    }

    private int getPosicaoPaciente() {

        int posPaciente = tabela.getSelectedRow();

        if (posPaciente == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um paciente");
        }

        return posPaciente;
    }

    private void excluirPaciente(int posPaciente) {

        if (posPaciente >= 0) {

            String[] options = {"Sim", "Não"};

            int deletar = JOptionPane.showOptionDialog(
                    rootPane,
                    "Tem certeza que deseja excluir?",
                    "Exclusão de paciente",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
            );

            if (deletar == 0) {

                pacientesLista.remove(posPaciente);

                atualizarTabela();
            } else {

                tabela.clearSelection();
            }
        }
    }

    public void atualizarTabela() {

        if (!pacientesLista.isEmpty()) {

            Pacientes paciente;

            tableModel = new DefaultTableModel(tableColumns, 0);

            for (int i = 0; i < pacientesLista.size(); i++) {

                paciente = pacientesLista.get(i);

                String[] rowData = {paciente.getNome(), paciente.getTelefone(), paciente.getCpf(), paciente.getData(), paciente.getePaciente(), paciente.getConsultaR()};

                /*
             * Agora adicionamos o vetor de dados na tableModel
                 */
                tableModel.addRow(rowData);
            }

            tabela.setModel(tableModel);
        } else {

            tableModel = new DefaultTableModel(tableColumns, 0);
            tabela.setModel(tableModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        nConsulta = new javax.swing.JButton();
        exConsulta = new javax.swing.JButton();
        atConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Boas Vinda ao Sistema de Agendamento");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente", "Telefone", "CPF", "Data", "Já é paciente", "Consulta Realizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        nConsulta.setText("Nova Consulta");
        nConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nConsultaActionPerformed(evt);
            }
        });

        exConsulta.setText("Excluir Consulta");
        exConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exConsultaActionPerformed(evt);
            }
        });

        atConsulta.setText("Finalizar Consulta");
        atConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exConsulta)
                .addGap(26, 26, 26)
                .addComponent(atConsulta)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nConsulta)
                    .addComponent(exConsulta)
                    .addComponent(atConsulta))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nConsultaActionPerformed
        CadastroConsulta cadastroConsulta = new CadastroConsulta();
        cadastroConsulta.mostraTela(this);
    }//GEN-LAST:event_nConsultaActionPerformed

    private void atConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atConsultaActionPerformed
        finalizarConsulta(getPosicaoPaciente());
    }//GEN-LAST:event_atConsultaActionPerformed

    private void exConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exConsultaActionPerformed
        excluirPaciente(getPosicaoPaciente());
    }//GEN-LAST:event_exConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atConsulta;
    private javax.swing.JButton exConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nConsulta;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
